name: WebAssembly

on: [push,pull_request]

jobs:
  build-wasm:
    name: "Build WebAssembly"
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: true

    - uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.11'

    - name: Build
      run: |
        pnpm build

    - name: Test
      run: |
        pnpm test
